### PR TITLE
Add flag to change the address to host on.

### PR DESCRIPTION
**Pull request by Solirs**

### CODE REVIEW

**Review by hozzer — CHANGES_REQUESTED** [review]
ListenAndServe takes an address which is in the form "host:port". Might I suggest instead of `ip` and `i` we use `host` and `h`?

**Comment by joaoofreitas** [comment]
@Solirs @hozzer

Thanks for your contributions.
Can you explain me why is it important to change the address? Isn't it supposed to just be `0.0.0.0`?

Thank you.

**Comment by Solirs** [comment]
@joaoofreitas 
It can be preferable to use 127.0.0.1 when testing to avoid exposing it to the network, so having a flag to do so can come in handy in some situations.

**Comment by Solirs** [comment]
Soo is this getting merged?

**Comment by joaoofreitas** [comment]
As soon as I can review and test it :)

**Comment by joaoofreitas** [comment]
Looks good to me.

**Pull request merged**
